version: '3.8'
services:
  api:
    build:
      context: ./api
    volumes:
      - ./api/data:/var/www/html/data
      - ./api:/var/www/html
    ports:
      - "8000:8000"
  app:
    build:
      context: ./web 
      dockerfile: Dockerfile
    ports:
      - "5173:80" 
    volumes:
      - ./web:/app 